classicos/Site/Controllers/TeamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Data.Context;
using Domain.Entities;
using Data.Repositories;
using Site.Helpers;
using Microsoft.AspNetCore.Http;
using Site.Models;

namespace Site.Controllers
{
    public class TeamsController : Controller
    {
        private readonly ClassicosContext _context;
        private readonly TeamRepository _teamRepository = new TeamRepository();
        private readonly ConfederationRepository _confRepository = new ConfederationRepository();
        private readonly FileUploadHelper _fileUploadHelper = new FileUploadHelper();
        protected readonly MatchRepository _matchRepository = new MatchRepository();
        protected readonly MatchHelper _matchHelper = new MatchHelper();

        public TeamsController(ClassicosContext context)
        {
            _context = context;
        }

        // GET: Teams
        [ResponseCache(Duration =1200)]
        public IActionResult Index(string order = "", int confederation = 0)
        {
            
            var teams = _teamRepository.GetTeams(confederation);
            var output = new List<TeamDetailViewModel>();

            foreach(var t in teams)                
                output.Add(_matchHelper.GetDetails(t, false));           

            switch(order)
            {
                case "perf":
                    output = output.OrderByDescending(x => x.PerformanceRecord).ToList();
                    break;
                case "wins":
                    output = output.OrderByDescending(x => x.Wins).ToList();
                    break;
                case "matches":
                    output = output.OrderByDescending(x => x.TotalPlayed).ToList();
                    break;
                case "draws":
                    output = output.OrderByDescending(x => x.Draws).ToList();
                    break;
                case "losses":
                    output = output.OrderByDescending(x => x.Losses).ToList();
                    break;
                case "goalsscored":
                    output = output.OrderByDescending(x => x.GoalsScored).ToList();
                    break;
                case "goalsagainst":
                    output = output.OrderByDescending(x => x.GoalsAgainst).ToList();
                    break;
                case "goaldiff":
                    output = output.OrderByDescending(x => x.GoalDifference).ToList();
                    break;
                case "goalsscoredaverage":
                    output = output.OrderByDescending(x => x.GoalsScoredAverage).ToList();
                    break;
                case "goalsagainstaverage":
                    output = output.OrderByDescending(x => x.GoalsAgainstAverage).ToList();
                    break;
                case "est":
                    output = output.OrderBy(x => x.EstablishedAt).ToList();
                    break;
                default:
                    output = output.OrderBy(x => x.Name).ToList();
                    break;
            }          

            return View(output);
        }

        // GET: Teams/Details/5
        public IActionResult Details(string id)
        {
            int intId = 0;
            Team team;
            int.TryParse(id, out intId);
            if (intId == 0 && id == string.Empty)            
                return NotFound();
            else
            {
                if (intId != 0)
                    team = _teamRepository.GetById(intId);                
                else                
                    team = _teamRepository.GetTeamByCode(id);


                if (team == null)
                    return NotFound();

                team.Confederation = _confRepository.GetById(team.ConfederationId);


            }

            

            return View(_matchHelper.GetDetails(team, true));
        }

        // GET: Teams/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Teams/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TeamId,Name,Crest,EmojiFlag,TeamCode,IsPublished")] Team team, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                team.Crest = team.Name + ".png";
                var ok = await _fileUploadHelper.UploadFile("wwwroot\\assets\\teams", file, team.Crest);                
                team.Created = DateTime.Now;
                team.Updated = DateTime.Now;
                team.TeamCode = team.TeamCode.ToUpper();
                _context.Add(team);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(team);
        }

        // GET: Teams/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Teams.SingleOrDefaultAsync(m => m.TeamId == id);
            if (team == null)
            {
                return NotFound();
            }
            return View(team);
        }

        // POST: Teams/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TeamId,ConfederationId,EstablishedAt,HomeAt,NickName,FullName,Name,Crest,EmojiFlag,TeamCode,IsPublished")] Team team)
        {
            if (id != team.TeamId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var ok = "";
                    if (Request.Form.Files.Count() > 0)
                       ok = await _fileUploadHelper.UploadFile("wwwroot\\assets\\teams", Request.Form.Files[0], team.Crest);

                    team.Updated = DateTime.Now;
                    team.TeamCode = team.TeamCode.ToUpper();
                    _context.Update(team);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeamExists(team.TeamId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", new { id = team.TeamId});
            }
            return View(team);
        }

        // GET: Teams/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var team = await _context.Teams
                .SingleOrDefaultAsync(m => m.TeamId == id);
            if (team == null)
            {
                return NotFound();
            }

            return View(team);
        }

        // POST: Teams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var team = await _context.Teams.SingleOrDefaultAsync(m => m.TeamId == id);
            _context.Teams.Remove(team);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TeamExists(int id)
        {
            return _context.Teams.Any(e => e.TeamId == id);
        }
        
    }
}

classicos/Site/Controllers/VenuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Data.Context;
using Domain.Entities;
using Data.Repositories;
using Site.Models;

namespace Site.Controllers
{
    public class VenuesController : Controller
    {
        private readonly ClassicosContext _context;
        protected readonly TeamRepository _teamRepository = new TeamRepository();
        protected readonly MatchRepository _matchRepository = new MatchRepository();
        protected readonly ConfederationRepository _confRepository = new ConfederationRepository();
        protected readonly VenueRepository _venueRepository = new VenueRepository();

        public VenuesController(ClassicosContext context)
        {
            _context = context;
        }

        // GET: Venues
        public IActionResult Index(int page = 1, int teamId = 0, int confederationId = 0, string locality = "")
        {
            var skip = (page - 1) * 15;
            var take = 15;            
            
            var model = new VenuesIndexViewModel(_venueRepository.GetFiltered(teamId,confederationId, locality).Skip(skip).Take(take));
            var count = _venueRepository.GetFiltered(teamId, confederationId, locality).Count();
            ViewBag.TotalPages = (int)Math.Ceiling(Decimal.Divide(count, take));
            ViewBag.Count = count;
            model.Teams = new SelectList(_teamRepository.GetMany(x => x.IsPublished), "TeamId", "Name", teamId);
            model.Confederations = new SelectList(_confRepository.GetMany(x => x.IsPublished), "ConfederationId", "Name", confederationId);
            model.Localities = new SelectList(_venueRepository.GetLocalities(), locality);
            return View(model);
        }

        // GET: Venues/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venue = await _context.Venues
                .Include(v => v.Team)
                .FirstOrDefaultAsync(m => m.VenueId == id);
            if (venue == null)
            {
                return NotFound();
            }

            return View(venue);
        }

        // GET: Venues/Create
        public IActionResult Create()
        {
            ViewData["TeamId"] = new SelectList(_context.Teams, "TeamId", "Name");
            return View();
        }

        // POST: Venues/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VenueId,Name,Locality,Capacity,TeamId,Created,Updated,IsPublished,IsDeleted")] Venue venue)
        {
            if (ModelState.IsValid)
            {
                _context.Add(venue);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["TeamId"] = new SelectList(_context.Teams, "TeamId", "Crest", venue.TeamId);
            return View(venue);
        }

        // GET: Venues/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venue = await _context.Venues.FindAsync(id);
            if (venue == null)
            {
                return NotFound();
            }
            ViewData["TeamId"] = new SelectList(_context.Teams, "TeamId", "Crest", venue.TeamId);
            return View(venue);
        }

        // POST: Venues/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("VenueId,Name,Locality,Capacity,TeamId,Created,Updated,IsPublished,IsDeleted")] Venue venue)
        {
            if (id != venue.VenueId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(venue);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VenueExists(venue.VenueId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TeamId"] = new SelectList(_context.Teams, "TeamId", "Crest", venue.TeamId);
            return View(venue);
        }

        // GET: Venues/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venue = await _context.Venues
                .Include(v => v.Team)
                .FirstOrDefaultAsync(m => m.VenueId == id);
            if (venue == null)
            {
                return NotFound();
            }

            return View(venue);
        }

        // POST: Venues/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var venue = await _context.Venues.FindAsync(id);
            _context.Venues.Remove(venue);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VenueExists(int id)
        {
            return _context.Venues.Any(e => e.VenueId == id);
        }

        public JsonResult LoadData(int id)
        {
            try
            {
                var c = _teamRepository.GetById(id);
                var m = _matchRepository.GetMatchesByLoc(c.TeamCode);
                int cont = 0;
                foreach (var item in m)
                {
                    _venueRepository.Add(new Venue
                    {
                        Capacity = 10000,
                        Created = DateTime.Now,
                        Updated = DateTime.Now,
                        IsPublished = true,
                        TeamId = id,
                        Locality = item.Locality,
                        Name = item.Venue,
                    });
                    cont++;
                }
                return Json(new { Country = c.TeamCode, Total = cont, venues = m });
            }
            catch
            {
                return Json(new { Error = "Country not Found" });
            }
            
        }
    }
}

classicos/Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Site</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="~/lib/bootstrap-combobox/css/bootstrap-combobox.css" rel="stylesheet">


    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link href="~/lib/bootstrap-combobox/css/bootstrap-combobox.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Site</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Matches" asp-action="Index">Matches</a></li>
                    <li><a asp-area="" asp-controller="Teams" asp-action="Index">Teams</a></li>
                    <li><a asp-area="" asp-controller="Competitions" asp-action="Index">Competitions</a></li>
                    <li><a asp-area="" asp-controller="Confederations" asp-action="Index">Confederations</a></li>
                    <li><a asp-area="" asp-controller="Venues" asp-action="Index">Venues</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Site</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/bootstrap-combobox/js/bootstrap-combobox.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <script src="~/lib/bootstrap-combobox/js/bootstrap-combobox.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>